console.log("somestringtext"[3]) ;
console.log("éléphant"[1]) ;
console.log("animal".length) ;
console.log("animal".length - 1) ;
console.log("yesJOHN".toUpperCase()) ;
console.log("hey friends call me"[2] === "y") ;
console.log("animal dans la forêt".length > 20) ;
console.log("bonjour ranger".indexOf("r")) ;
console.log("éléphant".indexOf("e")) ;
console.log("chat"[5]) ;
console.log("chat".indexOf("x")) ;
console.log("cat".indexOf("C")) ;
